# uncomment this to enable dependabot PRs of GitHub Action version updates

# version: 2
# updates:
#   # Maintain dependencies for GitHub Actions
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "monthly"
