---
name: Build with Multi-Platform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    steps:

#NEW: ############################################################
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
#NEW: ############################################################

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
            
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: bretfisher/allhands22:03
          cache-from: type=gha
          cache-to: type=gha,mode=max
#NEW: ############################################################
          platforms: linux/amd64,linux/arm64,linux/arm/v7
#NEW: ############################################################
